# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kylian/Documents/Code/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kylian/Documents/Code/cpp/UserAnalysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kylian/Documents/Code/cpp/UserAnalysis/CMakeFiles /home/kylian/Documents/Code/cpp/UserAnalysis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kylian/Documents/Code/cpp/UserAnalysis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named user_analysis

# Build rule for target.
user_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_analysis
.PHONY : user_analysis

# fast build rule for target.
user_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis.dir/build.make CMakeFiles/user_analysis.dir/build
.PHONY : user_analysis/fast

#=============================================================================
# Target rules for targets named DatabaseHandlerTest

# Build rule for target.
DatabaseHandlerTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DatabaseHandlerTest
.PHONY : DatabaseHandlerTest

# fast build rule for target.
DatabaseHandlerTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseHandlerTest.dir/build.make CMakeFiles/DatabaseHandlerTest.dir/build
.PHONY : DatabaseHandlerTest/fast

#=============================================================================
# Target rules for targets named LogGeneratorTest

# Build rule for target.
LogGeneratorTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LogGeneratorTest
.PHONY : LogGeneratorTest

# fast build rule for target.
LogGeneratorTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/build
.PHONY : LogGeneratorTest/fast

src/common/ConfigReader.o: src/common/ConfigReader.cpp.o
.PHONY : src/common/ConfigReader.o

# target to build an object file
src/common/ConfigReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/ConfigReader.cpp.o
.PHONY : src/common/ConfigReader.cpp.o

src/common/ConfigReader.i: src/common/ConfigReader.cpp.i
.PHONY : src/common/ConfigReader.i

# target to preprocess a source file
src/common/ConfigReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/ConfigReader.cpp.i
.PHONY : src/common/ConfigReader.cpp.i

src/common/ConfigReader.s: src/common/ConfigReader.cpp.s
.PHONY : src/common/ConfigReader.s

# target to generate assembly for a file
src/common/ConfigReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/ConfigReader.cpp.s
.PHONY : src/common/ConfigReader.cpp.s

src/common/DatabaseHandler.o: src/common/DatabaseHandler.cpp.o
.PHONY : src/common/DatabaseHandler.o

# target to build an object file
src/common/DatabaseHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/DatabaseHandler.cpp.o
.PHONY : src/common/DatabaseHandler.cpp.o

src/common/DatabaseHandler.i: src/common/DatabaseHandler.cpp.i
.PHONY : src/common/DatabaseHandler.i

# target to preprocess a source file
src/common/DatabaseHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/DatabaseHandler.cpp.i
.PHONY : src/common/DatabaseHandler.cpp.i

src/common/DatabaseHandler.s: src/common/DatabaseHandler.cpp.s
.PHONY : src/common/DatabaseHandler.s

# target to generate assembly for a file
src/common/DatabaseHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/DatabaseHandler.cpp.s
.PHONY : src/common/DatabaseHandler.cpp.s

src/common/LogGenerator.o: src/common/LogGenerator.cpp.o
.PHONY : src/common/LogGenerator.o

# target to build an object file
src/common/LogGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/LogGenerator.cpp.o
.PHONY : src/common/LogGenerator.cpp.o

src/common/LogGenerator.i: src/common/LogGenerator.cpp.i
.PHONY : src/common/LogGenerator.i

# target to preprocess a source file
src/common/LogGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/LogGenerator.cpp.i
.PHONY : src/common/LogGenerator.cpp.i

src/common/LogGenerator.s: src/common/LogGenerator.cpp.s
.PHONY : src/common/LogGenerator.s

# target to generate assembly for a file
src/common/LogGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/src/common/LogGenerator.cpp.s
.PHONY : src/common/LogGenerator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis.dir/build.make CMakeFiles/user_analysis.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis.dir/build.make CMakeFiles/user_analysis.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis.dir/build.make CMakeFiles/user_analysis.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/DatabaseHandler_test.o: tests/DatabaseHandler_test.cpp.o
.PHONY : tests/DatabaseHandler_test.o

# target to build an object file
tests/DatabaseHandler_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseHandlerTest.dir/build.make CMakeFiles/DatabaseHandlerTest.dir/tests/DatabaseHandler_test.cpp.o
.PHONY : tests/DatabaseHandler_test.cpp.o

tests/DatabaseHandler_test.i: tests/DatabaseHandler_test.cpp.i
.PHONY : tests/DatabaseHandler_test.i

# target to preprocess a source file
tests/DatabaseHandler_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseHandlerTest.dir/build.make CMakeFiles/DatabaseHandlerTest.dir/tests/DatabaseHandler_test.cpp.i
.PHONY : tests/DatabaseHandler_test.cpp.i

tests/DatabaseHandler_test.s: tests/DatabaseHandler_test.cpp.s
.PHONY : tests/DatabaseHandler_test.s

# target to generate assembly for a file
tests/DatabaseHandler_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DatabaseHandlerTest.dir/build.make CMakeFiles/DatabaseHandlerTest.dir/tests/DatabaseHandler_test.cpp.s
.PHONY : tests/DatabaseHandler_test.cpp.s

tests/LogGenerator_test.o: tests/LogGenerator_test.cpp.o
.PHONY : tests/LogGenerator_test.o

# target to build an object file
tests/LogGenerator_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/tests/LogGenerator_test.cpp.o
.PHONY : tests/LogGenerator_test.cpp.o

tests/LogGenerator_test.i: tests/LogGenerator_test.cpp.i
.PHONY : tests/LogGenerator_test.i

# target to preprocess a source file
tests/LogGenerator_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/tests/LogGenerator_test.cpp.i
.PHONY : tests/LogGenerator_test.cpp.i

tests/LogGenerator_test.s: tests/LogGenerator_test.cpp.s
.PHONY : tests/LogGenerator_test.s

# target to generate assembly for a file
tests/LogGenerator_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/tests/LogGenerator_test.cpp.s
.PHONY : tests/LogGenerator_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... DatabaseHandlerTest"
	@echo "... LogGeneratorTest"
	@echo "... common"
	@echo "... user_analysis"
	@echo "... src/common/ConfigReader.o"
	@echo "... src/common/ConfigReader.i"
	@echo "... src/common/ConfigReader.s"
	@echo "... src/common/DatabaseHandler.o"
	@echo "... src/common/DatabaseHandler.i"
	@echo "... src/common/DatabaseHandler.s"
	@echo "... src/common/LogGenerator.o"
	@echo "... src/common/LogGenerator.i"
	@echo "... src/common/LogGenerator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/DatabaseHandler_test.o"
	@echo "... tests/DatabaseHandler_test.i"
	@echo "... tests/DatabaseHandler_test.s"
	@echo "... tests/LogGenerator_test.o"
	@echo "... tests/LogGenerator_test.i"
	@echo "... tests/LogGenerator_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

