# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kylian/Documents/Code/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kylian/Documents/Code/cpp/UserAnalysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kylian/Documents/Code/cpp/UserAnalysis/CMakeFiles /home/kylian/Documents/Code/cpp/UserAnalysis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kylian/Documents/Code/cpp/UserAnalysis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named user_analysis_app

# Build rule for target.
user_analysis_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 user_analysis_app
.PHONY : user_analysis_app

# fast build rule for target.
user_analysis_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/build
.PHONY : user_analysis_app/fast

#=============================================================================
# Target rules for targets named masternode_test

# Build rule for target.
masternode_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 masternode_test
.PHONY : masternode_test

# fast build rule for target.
masternode_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/build
.PHONY : masternode_test/fast

#=============================================================================
# Target rules for targets named databasehandler_test

# Build rule for target.
databasehandler_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 databasehandler_test
.PHONY : databasehandler_test

# fast build rule for target.
databasehandler_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/build
.PHONY : databasehandler_test/fast

#=============================================================================
# Target rules for targets named loggenerator_test

# Build rule for target.
loggenerator_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loggenerator_test
.PHONY : loggenerator_test

# fast build rule for target.
loggenerator_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loggenerator_test.dir/build.make CMakeFiles/loggenerator_test.dir/build
.PHONY : loggenerator_test/fast

#=============================================================================
# Target rules for targets named workernode_test

# Build rule for target.
workernode_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 workernode_test
.PHONY : workernode_test

# fast build rule for target.
workernode_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/build
.PHONY : workernode_test/fast

generated/user_analysis.grpc.pb.o: generated/user_analysis.grpc.pb.cc.o
.PHONY : generated/user_analysis.grpc.pb.o

# target to build an object file
generated/user_analysis.grpc.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/generated/user_analysis.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/generated/user_analysis.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/generated/user_analysis.grpc.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/generated/user_analysis.grpc.pb.cc.o
.PHONY : generated/user_analysis.grpc.pb.cc.o

generated/user_analysis.grpc.pb.i: generated/user_analysis.grpc.pb.cc.i
.PHONY : generated/user_analysis.grpc.pb.i

# target to preprocess a source file
generated/user_analysis.grpc.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/generated/user_analysis.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/generated/user_analysis.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/generated/user_analysis.grpc.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/generated/user_analysis.grpc.pb.cc.i
.PHONY : generated/user_analysis.grpc.pb.cc.i

generated/user_analysis.grpc.pb.s: generated/user_analysis.grpc.pb.cc.s
.PHONY : generated/user_analysis.grpc.pb.s

# target to generate assembly for a file
generated/user_analysis.grpc.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/generated/user_analysis.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/generated/user_analysis.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/generated/user_analysis.grpc.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/generated/user_analysis.grpc.pb.cc.s
.PHONY : generated/user_analysis.grpc.pb.cc.s

generated/user_analysis.pb.o: generated/user_analysis.pb.cc.o
.PHONY : generated/user_analysis.pb.o

# target to build an object file
generated/user_analysis.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/generated/user_analysis.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/generated/user_analysis.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/generated/user_analysis.pb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/generated/user_analysis.pb.cc.o
.PHONY : generated/user_analysis.pb.cc.o

generated/user_analysis.pb.i: generated/user_analysis.pb.cc.i
.PHONY : generated/user_analysis.pb.i

# target to preprocess a source file
generated/user_analysis.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/generated/user_analysis.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/generated/user_analysis.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/generated/user_analysis.pb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/generated/user_analysis.pb.cc.i
.PHONY : generated/user_analysis.pb.cc.i

generated/user_analysis.pb.s: generated/user_analysis.pb.cc.s
.PHONY : generated/user_analysis.pb.s

# target to generate assembly for a file
generated/user_analysis.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/generated/user_analysis.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/generated/user_analysis.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/generated/user_analysis.pb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/generated/user_analysis.pb.cc.s
.PHONY : generated/user_analysis.pb.cc.s

src/common/ConfigReader.o: src/common/ConfigReader.cpp.o
.PHONY : src/common/ConfigReader.o

# target to build an object file
src/common/ConfigReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/ConfigReader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/common/ConfigReader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/src/common/ConfigReader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/common/ConfigReader.cpp.o
.PHONY : src/common/ConfigReader.cpp.o

src/common/ConfigReader.i: src/common/ConfigReader.cpp.i
.PHONY : src/common/ConfigReader.i

# target to preprocess a source file
src/common/ConfigReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/ConfigReader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/common/ConfigReader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/src/common/ConfigReader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/common/ConfigReader.cpp.i
.PHONY : src/common/ConfigReader.cpp.i

src/common/ConfigReader.s: src/common/ConfigReader.cpp.s
.PHONY : src/common/ConfigReader.s

# target to generate assembly for a file
src/common/ConfigReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/ConfigReader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/common/ConfigReader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/src/common/ConfigReader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/common/ConfigReader.cpp.s
.PHONY : src/common/ConfigReader.cpp.s

src/common/DatabaseHandler.o: src/common/DatabaseHandler.cpp.o
.PHONY : src/common/DatabaseHandler.o

# target to build an object file
src/common/DatabaseHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/DatabaseHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/common/DatabaseHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/src/common/DatabaseHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/common/DatabaseHandler.cpp.o
.PHONY : src/common/DatabaseHandler.cpp.o

src/common/DatabaseHandler.i: src/common/DatabaseHandler.cpp.i
.PHONY : src/common/DatabaseHandler.i

# target to preprocess a source file
src/common/DatabaseHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/DatabaseHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/common/DatabaseHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/src/common/DatabaseHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/common/DatabaseHandler.cpp.i
.PHONY : src/common/DatabaseHandler.cpp.i

src/common/DatabaseHandler.s: src/common/DatabaseHandler.cpp.s
.PHONY : src/common/DatabaseHandler.s

# target to generate assembly for a file
src/common/DatabaseHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/DatabaseHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/common/DatabaseHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/src/common/DatabaseHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/common/DatabaseHandler.cpp.s
.PHONY : src/common/DatabaseHandler.cpp.s

src/common/LogGenerator.o: src/common/LogGenerator.cpp.o
.PHONY : src/common/LogGenerator.o

# target to build an object file
src/common/LogGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/LogGenerator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loggenerator_test.dir/build.make CMakeFiles/loggenerator_test.dir/src/common/LogGenerator.cpp.o
.PHONY : src/common/LogGenerator.cpp.o

src/common/LogGenerator.i: src/common/LogGenerator.cpp.i
.PHONY : src/common/LogGenerator.i

# target to preprocess a source file
src/common/LogGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/LogGenerator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loggenerator_test.dir/build.make CMakeFiles/loggenerator_test.dir/src/common/LogGenerator.cpp.i
.PHONY : src/common/LogGenerator.cpp.i

src/common/LogGenerator.s: src/common/LogGenerator.cpp.s
.PHONY : src/common/LogGenerator.s

# target to generate assembly for a file
src/common/LogGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/common/LogGenerator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loggenerator_test.dir/build.make CMakeFiles/loggenerator_test.dir/src/common/LogGenerator.cpp.s
.PHONY : src/common/LogGenerator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/master/MasterNode.o: src/master/MasterNode.cpp.o
.PHONY : src/master/MasterNode.o

# target to build an object file
src/master/MasterNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/master/MasterNode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/master/MasterNode.cpp.o
.PHONY : src/master/MasterNode.cpp.o

src/master/MasterNode.i: src/master/MasterNode.cpp.i
.PHONY : src/master/MasterNode.i

# target to preprocess a source file
src/master/MasterNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/master/MasterNode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/master/MasterNode.cpp.i
.PHONY : src/master/MasterNode.cpp.i

src/master/MasterNode.s: src/master/MasterNode.cpp.s
.PHONY : src/master/MasterNode.s

# target to generate assembly for a file
src/master/MasterNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/master/MasterNode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/src/master/MasterNode.cpp.s
.PHONY : src/master/MasterNode.cpp.s

src/worker/WorkerNode.o: src/worker/WorkerNode.cpp.o
.PHONY : src/worker/WorkerNode.o

# target to build an object file
src/worker/WorkerNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/worker/WorkerNode.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/worker/WorkerNode.cpp.o
.PHONY : src/worker/WorkerNode.cpp.o

src/worker/WorkerNode.i: src/worker/WorkerNode.cpp.i
.PHONY : src/worker/WorkerNode.i

# target to preprocess a source file
src/worker/WorkerNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/worker/WorkerNode.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/worker/WorkerNode.cpp.i
.PHONY : src/worker/WorkerNode.cpp.i

src/worker/WorkerNode.s: src/worker/WorkerNode.cpp.s
.PHONY : src/worker/WorkerNode.s

# target to generate assembly for a file
src/worker/WorkerNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/user_analysis_app.dir/build.make CMakeFiles/user_analysis_app.dir/src/worker/WorkerNode.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/src/worker/WorkerNode.cpp.s
.PHONY : src/worker/WorkerNode.cpp.s

tests/DatabaseHandler_test.o: tests/DatabaseHandler_test.cpp.o
.PHONY : tests/DatabaseHandler_test.o

# target to build an object file
tests/DatabaseHandler_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/tests/DatabaseHandler_test.cpp.o
.PHONY : tests/DatabaseHandler_test.cpp.o

tests/DatabaseHandler_test.i: tests/DatabaseHandler_test.cpp.i
.PHONY : tests/DatabaseHandler_test.i

# target to preprocess a source file
tests/DatabaseHandler_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/tests/DatabaseHandler_test.cpp.i
.PHONY : tests/DatabaseHandler_test.cpp.i

tests/DatabaseHandler_test.s: tests/DatabaseHandler_test.cpp.s
.PHONY : tests/DatabaseHandler_test.s

# target to generate assembly for a file
tests/DatabaseHandler_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/databasehandler_test.dir/build.make CMakeFiles/databasehandler_test.dir/tests/DatabaseHandler_test.cpp.s
.PHONY : tests/DatabaseHandler_test.cpp.s

tests/LogGenerator_test.o: tests/LogGenerator_test.cpp.o
.PHONY : tests/LogGenerator_test.o

# target to build an object file
tests/LogGenerator_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loggenerator_test.dir/build.make CMakeFiles/loggenerator_test.dir/tests/LogGenerator_test.cpp.o
.PHONY : tests/LogGenerator_test.cpp.o

tests/LogGenerator_test.i: tests/LogGenerator_test.cpp.i
.PHONY : tests/LogGenerator_test.i

# target to preprocess a source file
tests/LogGenerator_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loggenerator_test.dir/build.make CMakeFiles/loggenerator_test.dir/tests/LogGenerator_test.cpp.i
.PHONY : tests/LogGenerator_test.cpp.i

tests/LogGenerator_test.s: tests/LogGenerator_test.cpp.s
.PHONY : tests/LogGenerator_test.s

# target to generate assembly for a file
tests/LogGenerator_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loggenerator_test.dir/build.make CMakeFiles/loggenerator_test.dir/tests/LogGenerator_test.cpp.s
.PHONY : tests/LogGenerator_test.cpp.s

tests/MasterNode_test.o: tests/MasterNode_test.cpp.o
.PHONY : tests/MasterNode_test.o

# target to build an object file
tests/MasterNode_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/tests/MasterNode_test.cpp.o
.PHONY : tests/MasterNode_test.cpp.o

tests/MasterNode_test.i: tests/MasterNode_test.cpp.i
.PHONY : tests/MasterNode_test.i

# target to preprocess a source file
tests/MasterNode_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/tests/MasterNode_test.cpp.i
.PHONY : tests/MasterNode_test.cpp.i

tests/MasterNode_test.s: tests/MasterNode_test.cpp.s
.PHONY : tests/MasterNode_test.s

# target to generate assembly for a file
tests/MasterNode_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/masternode_test.dir/build.make CMakeFiles/masternode_test.dir/tests/MasterNode_test.cpp.s
.PHONY : tests/MasterNode_test.cpp.s

tests/WorkerNode_test.o: tests/WorkerNode_test.cpp.o
.PHONY : tests/WorkerNode_test.o

# target to build an object file
tests/WorkerNode_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/tests/WorkerNode_test.cpp.o
.PHONY : tests/WorkerNode_test.cpp.o

tests/WorkerNode_test.i: tests/WorkerNode_test.cpp.i
.PHONY : tests/WorkerNode_test.i

# target to preprocess a source file
tests/WorkerNode_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/tests/WorkerNode_test.cpp.i
.PHONY : tests/WorkerNode_test.cpp.i

tests/WorkerNode_test.s: tests/WorkerNode_test.cpp.s
.PHONY : tests/WorkerNode_test.s

# target to generate assembly for a file
tests/WorkerNode_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/workernode_test.dir/build.make CMakeFiles/workernode_test.dir/tests/WorkerNode_test.cpp.s
.PHONY : tests/WorkerNode_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... databasehandler_test"
	@echo "... loggenerator_test"
	@echo "... masternode_test"
	@echo "... user_analysis_app"
	@echo "... workernode_test"
	@echo "... generated/user_analysis.grpc.pb.o"
	@echo "... generated/user_analysis.grpc.pb.i"
	@echo "... generated/user_analysis.grpc.pb.s"
	@echo "... generated/user_analysis.pb.o"
	@echo "... generated/user_analysis.pb.i"
	@echo "... generated/user_analysis.pb.s"
	@echo "... src/common/ConfigReader.o"
	@echo "... src/common/ConfigReader.i"
	@echo "... src/common/ConfigReader.s"
	@echo "... src/common/DatabaseHandler.o"
	@echo "... src/common/DatabaseHandler.i"
	@echo "... src/common/DatabaseHandler.s"
	@echo "... src/common/LogGenerator.o"
	@echo "... src/common/LogGenerator.i"
	@echo "... src/common/LogGenerator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/master/MasterNode.o"
	@echo "... src/master/MasterNode.i"
	@echo "... src/master/MasterNode.s"
	@echo "... src/worker/WorkerNode.o"
	@echo "... src/worker/WorkerNode.i"
	@echo "... src/worker/WorkerNode.s"
	@echo "... tests/DatabaseHandler_test.o"
	@echo "... tests/DatabaseHandler_test.i"
	@echo "... tests/DatabaseHandler_test.s"
	@echo "... tests/LogGenerator_test.o"
	@echo "... tests/LogGenerator_test.i"
	@echo "... tests/LogGenerator_test.s"
	@echo "... tests/MasterNode_test.o"
	@echo "... tests/MasterNode_test.i"
	@echo "... tests/MasterNode_test.s"
	@echo "... tests/WorkerNode_test.o"
	@echo "... tests/WorkerNode_test.i"
	@echo "... tests/WorkerNode_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

