# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kylian/Documents/Code/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kylian/Documents/Code/cpp/UserAnalysis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kylian/Documents/Code/cpp/UserAnalysis/CMakeFiles /home/kylian/Documents/Code/cpp/UserAnalysis//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kylian/Documents/Code/cpp/UserAnalysis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LogGenerator

# Build rule for target.
LogGenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LogGenerator
.PHONY : LogGenerator

# fast build rule for target.
LogGenerator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGenerator.dir/build.make CMakeFiles/LogGenerator.dir/build
.PHONY : LogGenerator/fast

#=============================================================================
# Target rules for targets named LogGeneratorTest

# Build rule for target.
LogGeneratorTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LogGeneratorTest
.PHONY : LogGeneratorTest

# fast build rule for target.
LogGeneratorTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/build
.PHONY : LogGeneratorTest/fast

src/LogGenerator.o: src/LogGenerator.cpp.o
.PHONY : src/LogGenerator.o

# target to build an object file
src/LogGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGenerator.dir/build.make CMakeFiles/LogGenerator.dir/src/LogGenerator.cpp.o
.PHONY : src/LogGenerator.cpp.o

src/LogGenerator.i: src/LogGenerator.cpp.i
.PHONY : src/LogGenerator.i

# target to preprocess a source file
src/LogGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGenerator.dir/build.make CMakeFiles/LogGenerator.dir/src/LogGenerator.cpp.i
.PHONY : src/LogGenerator.cpp.i

src/LogGenerator.s: src/LogGenerator.cpp.s
.PHONY : src/LogGenerator.s

# target to generate assembly for a file
src/LogGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGenerator.dir/build.make CMakeFiles/LogGenerator.dir/src/LogGenerator.cpp.s
.PHONY : src/LogGenerator.cpp.s

src/LogGenerator_test.o: src/LogGenerator_test.cpp.o
.PHONY : src/LogGenerator_test.o

# target to build an object file
src/LogGenerator_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/src/LogGenerator_test.cpp.o
.PHONY : src/LogGenerator_test.cpp.o

src/LogGenerator_test.i: src/LogGenerator_test.cpp.i
.PHONY : src/LogGenerator_test.i

# target to preprocess a source file
src/LogGenerator_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/src/LogGenerator_test.cpp.i
.PHONY : src/LogGenerator_test.cpp.i

src/LogGenerator_test.s: src/LogGenerator_test.cpp.s
.PHONY : src/LogGenerator_test.s

# target to generate assembly for a file
src/LogGenerator_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LogGeneratorTest.dir/build.make CMakeFiles/LogGeneratorTest.dir/src/LogGenerator_test.cpp.s
.PHONY : src/LogGenerator_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... LogGenerator"
	@echo "... LogGeneratorTest"
	@echo "... src/LogGenerator.o"
	@echo "... src/LogGenerator.i"
	@echo "... src/LogGenerator.s"
	@echo "... src/LogGenerator_test.o"
	@echo "... src/LogGenerator_test.i"
	@echo "... src/LogGenerator_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

